"""Repository 契约（CQ-P1-002 Slice A + R2 Slice B 域拆分）。

``PgRepository``（生产 PostgreSQL）与 ``DemoRepository``（测试内存 fake）双实现的
显式接口契约。方法面机器提取自 ``PgRepository``（101 公共方法，``inspect.signature``
生成，``DemoRepository`` 公共方法面与之零差异——见
``tests/backend/test_repository_contract.py`` contract test 守护）。

取代 ``pg_repository.py`` 顶部 docstring 所述的 "same interface, duck-typed"——双实现
一致性从此由机器契约兜底，不再靠人工对照 1600+/1200+ 行文件。这是 CQ-P1-002 的核心
收益，并为 CQ-P1-003（事务边界 UoW）提供 Protocol 基础。

R2 Slice B（2026-08-19，收敛 god object）：101 方法按实际调用聚类拆为 8 个域子
Protocol（Document/User/Folder/Term/Tag/Space/Ops/Search），``RepositoryProtocol``
改为聚合签名（8 子接口并集）。拆分动因与学科依据见
``docs/research/2026-08-18-code-directory-review.md`` §1.4（ISP / god object）；
22 个既有消费方零迁移（聚合层兼容）。

后续可选：
- Slice C（2026-08-21 部分完成）：单域 service 已收窄——auth / auth_reset →
  ``UserRepository``、vault_mounts → ``OpsRepository``。跨 2-5 域与跨 service
  委托的消费方（document / folder / imports / ai_polish 等）保持聚合
  ``RepositoryProtocol``：mypy 对 Union 属性取交集，跨域无法用子 Protocol
  并集收窄，逐模块评估后维持聚合更贴合实际依赖。

``@runtime_checkable`` 使 ``isinstance(repo, RepositoryProtocol)`` 可用（contract test
+ 运行时兜底校验）。Python ``Protocol`` 是结构化子类型，``PgRepository`` / ``DemoRepository``
显式继承仅为静态工具（IDE / mypy / pyright）识别，不改变运行时行为。
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from backend.model.entities import (
    AiDraft,
    DocExport,
    DocLink,
    DocLinkDraft,
    Document,
    DocumentChunk,
    DocumentPermission,
    DocumentVersion,
    Folder,
    ImportJob,
    QuickEntry,
    Session,
    Space,
    SpaceMember,
    SpaceMemberDetail,
    Tag,
    TagLink,
    Term,
    TermCategory,
    TermStatus,
    User,
    VaultMount,
)

# ---------------------------------------------------------------------------
# 域子 Protocol（R2 Slice B，2026-08-19）
# 按实际调用聚类拆分（16/18 个 service 跨 2-5 域调用，故聚合父接口保留兼容，
# service 注解收窄为子 Protocol 属后续 Slice C，另行裁决）。边界按「主要消费方」
# 归组（如 list_memberships 归 SpaceRepository），边界调整只影响分组不影响契约面。
# ---------------------------------------------------------------------------

@runtime_checkable
class DocumentRepository(Protocol):
    """文档与内容域：文档 CRUD / 版本 / 双链（doc + chunk 存储面 + doc_link）。"""

    def create_document(self, space_id: int, title: str, content_md: str, owner_id: int, permission: DocumentPermission, folder_id: int | None = None) -> Document: ...

    def delete_document(self, document_id: int) -> None: ...

    def find_document_id_by_title(self, space_id: int, title: str) -> int | None: ...

    def get_document(self, document_id: int) -> Document | None: ...

    def get_document_version(self, document_id: int, version_no: int) -> DocumentVersion | None: ...

    def list_doc_links(self, space_id: int, document_id: int, direction: str) -> list[DocLink]: ...

    def list_document_chunks(self, document_id: int) -> list[DocumentChunk]: ...

    def list_document_versions(self, document_id: int) -> list[DocumentVersion]: ...

    def list_visible_documents(self, user_id: int, space_id: int) -> list[Document]: ...

    def replace_document_chunks(self, document_id: int, chunk_texts: list[str]) -> list[DocumentChunk]: ...

    def replace_document_wikilinks(self, space_id: int, source_document_id: int, drafts: list[DocLinkDraft]) -> list[DocLink]: ...

    def require_document(self, document_id: int) -> Document: ...

    def restore_document_version(self, document_id: int, version_no: int, editor_id: int) -> Document: ...

    def update_document(self, document_id: int, title: str, content_md: str, permission: DocumentPermission, editor_id: int) -> Document: ...

    def upsert_manual_link(self, space_id: int, source_document_id: int, target_document_id: int | None, target_title: str, link_text: str) -> DocLink: ...

@runtime_checkable
class UserRepository(Protocol):
    """用户与会话域：用户查询 / 账号管理 / 会话 / 登录锁定 / 密码重置（user + session 两表一族）。"""

    def clear_reset_token(self, user_id: int, used_at: str) -> None: ...

    def create_session(self, user_id: int, current_space_id: int | None, token_hash: str, expires_at: str, client_ua: str | None = None, client_ip: str | None = None) -> Session: ...

    def create_user_with_personal_space(self, email: str, external_id: str, name: str, password_hash: str) -> User: ...

    def find_session_by_token_hash(self, token_hash: str) -> Session | None: ...

    def find_user_by_email(self, email: str) -> User | None: ...

    def find_user_by_external_id(self, external_id: str) -> User | None: ...

    def find_user_by_id(self, user_id: int) -> User | None: ...

    def find_user_by_reset_token_hash(self, token_hash: str) -> User | None: ...

    def first_space_id_for_user(self, user_id: int) -> int | None: ...

    def list_sessions(self, user_id: int) -> list[Session]: ...

    def list_users(self, q: str = "", role: str = "", status: str = "") -> list[User]: ...

    def record_login_failure(self, user_id: int) -> int: ...

    def reset_login_failures(self, user_id: int) -> None: ...

    def revoke_all_sessions(self, user_id: int) -> int: ...

    def revoke_session(self, session_id: int, user_id: int) -> bool: ...

    def revoke_user_sessions(self, user_id: int) -> int: ...

    def search_users(self, q: str = "") -> list[User]: ...

    def set_locked_until(self, user_id: int, locked_until: str) -> None: ...

    def set_reset_token(self, user_id: int, token_hash: str, expires_at: str) -> None: ...

    def set_user_status(self, user_id: int, status: str) -> User | None: ...

    def update_password(self, user_id: int, password_hash: str) -> None: ...

    def update_session_space(self, session_id: int, space_id: int) -> Session: ...

    def update_user_role(self, user_id: int, role: str) -> User | None: ...

@runtime_checkable
class FolderRepository(Protocol):
    """文件夹域：树结构 CRUD / 移动 / 排序 / 空判定 + 文档-文件夹挂接。"""

    def create_folder(self, space_id: int, parent_id: int | None, name: str, created_by: int) -> Folder: ...

    def delete_folder(self, folder_id: int) -> None: ...

    def find_folder_by_name(self, space_id: int, parent_id: int | None, name: str) -> Folder | None: ...

    def get_folder(self, folder_id: int) -> Folder | None: ...

    def is_descendant_folder(self, space_id: int, ancestor_id: int, candidate_id: int) -> bool: ...

    def is_folder_empty(self, space_id: int, folder_id: int) -> bool: ...

    def list_folder_document_ids(self, space_id: int, folder_id: int) -> list[int]: ...

    def list_folders(self, space_id: int) -> list[Folder]: ...

    def move_folder(self, folder_id: int, parent_id: int | None) -> Folder | None: ...

    def rename_folder(self, folder_id: int, name: str) -> Folder | None: ...

    def reorder_folders(self, space_id: int, ordered_folder_ids: list[int]) -> None: ...

    def set_document_folder(self, document_id: int, folder_id: int | None) -> None: ...

@runtime_checkable
class TermRepository(Protocol):
    """术语域：术语 CRUD + 领域树（term + term_category 两表一族）。"""

    def create_term(self, space_id: int | None, term: str, definition: str, aliases: list[str], owner_id: int, status: TermStatus, source_document_id: int | None = None, category_id: int | None = None, category: str | None = None, source: str | None = None) -> Term: ...

    def create_term_category(self, space_id: int, parent_id: int | None, name: str, created_by: int) -> TermCategory: ...

    def delete_term(self, term_id: int) -> None: ...

    def delete_term_category(self, category_id: int) -> None: ...

    def find_term_category_by_name(self, space_id: int, parent_id: int | None, name: str) -> TermCategory | None: ...

    def get_term(self, term_id: int) -> Term | None: ...

    def get_term_category(self, category_id: int) -> TermCategory | None: ...

    def is_descendant_term_category(self, space_id: int, ancestor_id: int, candidate_id: int) -> bool: ...

    def is_term_category_empty(self, space_id: int, category_id: int) -> bool: ...

    def list_term_categories(self, space_id: int) -> list[TermCategory]: ...

    def list_term_category_term_ids(self, space_id: int, category_id: int) -> list[int]: ...

    def list_terms(self) -> list[Term]: ...

    def move_term_category(self, category_id: int, parent_id: int | None) -> TermCategory | None: ...

    def rename_term_category(self, category_id: int, name: str) -> TermCategory | None: ...

    def reorder_term_categories(self, space_id: int, ordered_category_ids: list[int]) -> None: ...

    def require_term(self, term_id: int) -> Term: ...

    def update_term(self, term_id: int, term: str, definition: str, aliases: list[str], status: TermStatus, source_document_id: int | None = None, category_id: int | None = None, category: str | None = None, source: str | None = None) -> Term: ...

@runtime_checkable
class TagRepository(Protocol):
    """标签域：标签 CRUD + 文档-标签关联（tag + tag_link）。"""

    def create_tag(self, space_id: int, name: str, normalized_name: str, created_by: int, color: str | None = None, description: str | None = None) -> Tag: ...

    def get_tag(self, tag_id: int) -> Tag | None: ...

    def list_document_tag_links(self, document_id: int) -> list[TagLink]: ...

    def list_tag_document_ids(self, tag_id: int) -> list[int]: ...

    def list_tags(self, space_id: int, q: str | None = None, status: str | None = "active") -> list[Tag]: ...

    def remove_document_tag(self, tag_id: int, document_id: int) -> bool: ...

    def update_tag(self, tag_id: int, name: str | None = None, normalized_name: str | None = None, color: str | None = None, description: str | None = None, status: str | None = None) -> Tag | None: ...

    def upsert_document_tag(self, tag_id: int, document_id: int, link_source: str, created_by: int) -> TagLink: ...

@runtime_checkable
class SpaceRepository(Protocol):
    """空间与成员域：空间查询 / 成员增删改 / 管理员计数 / 成员关系。"""

    def add_space_member(self, space_id: int, user_id: int, role: str) -> SpaceMemberDetail | None: ...

    def count_space_admins(self, space_id: int) -> int: ...

    def find_space(self, space_id: int) -> Space | None: ...

    # INTERNAL（CQ-P1-004）：同 list_documents，仅系统内部路径使用。
    def list_memberships(self) -> list[SpaceMember]: ...

    def list_space_members(self, space_id: int) -> list[SpaceMemberDetail]: ...

    def list_spaces(self) -> list[Space]: ...

    def remove_space_member(self, space_id: int, user_id: int) -> bool: ...

    def update_space_member_role(self, space_id: int, user_id: int, role: str) -> SpaceMemberDetail | None: ...

@runtime_checkable
class OpsRepository(Protocol):
    """运行支撑域：导入任务 / 导出任务 / 快速录入 / AI 草稿 / Vault 挂载（低频运维面）。"""

    def complete_import_job(self, import_id: int, parsed_doc_id: int, chunk_count: int) -> ImportJob: ...

    def create_ai_draft(self, space_id: int, document_id: int, user_id: int, mode: str, input_excerpt_hash: str | None = None, prompt_summary: str = "", output_md: str = "", cited_chunk_ids: tuple[int, ...] = (), status: str = "generated") -> AiDraft: ...

    def create_doc_export(self, space_id: int, document_id: int, requested_by: int, version_no: int, status: str = "queued", artifact_path: str | None = None, error_message: str | None = None) -> DocExport: ...

    def create_import_job(self, space_id: int, source_filename: str, created_by: int) -> ImportJob: ...

    def create_quick_entry(self, space_id: int, owner_id: int, title: str, content_md: str = "", source: str | None = None, target_document_id: int | None = None, created_document_id: int | None = None, status: str = "draft") -> QuickEntry: ...

    def fail_import_job(self, import_id: int, error: str) -> ImportJob: ...

    def get_doc_export(self, export_id: int) -> DocExport | None: ...

    def get_quick_entry(self, entry_id: int) -> QuickEntry | None: ...

    def list_quick_entries(self, space_id: int, owner_id: int, status: str | None = None) -> list[QuickEntry]: ...

    def list_vault_mounts(self, user_id: int) -> list[VaultMount]: ...

    def require_import_job(self, import_id: int) -> ImportJob: ...

    def update_doc_export(self, export_id: int, status: str, artifact_path: str | None = None, error_message: str | None = None) -> DocExport: ...

    def update_quick_entry(self, entry_id: int, status: str | None = None, target_document_id: int | None = None, created_document_id: int | None = None) -> QuickEntry | None: ...

    def upsert_vault_mount(self, user_id: int, device_id: str, mount_name: str, source_type: str, auth_status: str = "granted") -> VaultMount: ...

@runtime_checkable
class SearchRepository(Protocol):
    """检索域：RAG 召回 / 全文检索 / 全量分块与全量文档（INTERNAL 内部路径为主）。"""

    def list_all_document_chunks(self) -> list[DocumentChunk]: ...

    # INTERNAL（CQ-P1-004）：无权限 scope 的全量方法，仅系统内部路径（启动回填等）使用；
    # 用户态查询必须用 list_visible_documents(user_id, space_id) 或显式成员校验。
    def list_documents(self) -> list[Document]: ...

    def recall_chunks(self, document_ids: list[int], query: str, limit: int, threshold: float = 0.6) -> list[DocumentChunk]: ...

    def search_chunks(self, document_ids: list[int], query: str, limit: int) -> list[DocumentChunk]: ...

# ---------------------------------------------------------------------------
# 聚合契约（兼容层）：双实现共同满足的全量方法面。
# 方法面 = 8 个域子 Protocol 的并集；contract test 守护并集与父接口 / 双实现零漂移。
# 22 个既有消费方（service/api/tests）继续 import 本接口，零迁移成本。
# ---------------------------------------------------------------------------
@runtime_checkable
class RepositoryProtocol(
    DocumentRepository,
    UserRepository,
    FolderRepository,
    TermRepository,
    TagRepository,
    SpaceRepository,
    OpsRepository,
    SearchRepository,
    Protocol,
):
    """持久化层双实现聚合契约（PgRepository 生产 / DemoRepository 测试 fake）。

    方法面机器提取自 PgRepository（现按域分组为 8 个子 Protocol）；contract test
    验证 ``PgRepository`` / ``DemoRepository`` 公共方法面与本契约零漂移。
    """
