"""Repository 契约（CQ-P1-002 Slice A）。

``PgRepository``（生产 PostgreSQL）与 ``DemoRepository``（测试内存 fake）双实现的
显式接口契约。方法面机器提取自 ``PgRepository``（98 公共方法，``inspect.signature``
生成，``DemoRepository`` 公共方法面与之零差异——见
``tests/backend/test_repository_contract.py`` contract test 守护）。

取代 ``pg_repository.py`` 顶部 docstring 所述的 "same interface, duck-typed"——双实现
一致性从此由机器契约兜底，不再靠人工对照 1600+/1200+ 行文件。这是 CQ-P1-002 的核心
收益，并为 CQ-P1-003（事务边界 UoW）提供 Protocol 基础。

后续可选：
- Slice B：在此契约之上按域拆子 Protocol（``DocumentRepository`` / ``UserRepository`` 等），
  收敛 god object。
- Slice C：让 service 函数的 ``repository`` 参数注解为 ``RepositoryProtocol``（当前为裸
  ``repository`` 无类型），让静态检查 / IDE 识别。

``@runtime_checkable`` 使 ``isinstance(repo, RepositoryProtocol)`` 可用（contract test
+ 运行时兜底校验）。Python ``Protocol`` 是结构化子类型，``PgRepository`` / ``DemoRepository``
显式继承仅为静态工具（IDE / mypy / pyright）识别，不改变运行时行为。
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from backend.model.entities import (
    AiDraft,
    DocExport,
    DocLink,
    DocLinkDraft,
    Document,
    DocumentChunk,
    DocumentPermission,
    DocumentVersion,
    Folder,
    ImportJob,
    QuickEntry,
    Session,
    Space,
    SpaceMember,
    SpaceMemberDetail,
    Tag,
    TagLink,
    Term,
    TermCategory,
    TermStatus,
    User,
)


@runtime_checkable
class RepositoryProtocol(Protocol):
    """持久化层双实现契约（PgRepository 生产 / DemoRepository 测试 fake）。

    方法面机器提取自 PgRepository（字母序，避免手工分组出错）；contract test
    验证 ``PgRepository`` / ``DemoRepository`` 公共方法面与本契约零漂移。
    """

    # 方法面机器提取自 PgRepository（字母序）；contract test 守护双实现一致。

    def add_space_member(self, space_id: int, user_id: int, role: str) -> SpaceMemberDetail | None: ...
    def clear_reset_token(self, user_id: int, used_at: str) -> None: ...
    def complete_import_job(self, import_id: int, parsed_doc_id: int, chunk_count: int) -> ImportJob: ...
    def count_space_admins(self, space_id: int) -> int: ...
    def create_ai_draft(self, space_id: int, document_id: int, user_id: int, mode: str, input_excerpt_hash: str | None = None, prompt_summary: str = "", output_md: str = "", cited_chunk_ids: tuple[int, ...] = (), status: str = "generated") -> AiDraft: ...
    def create_doc_export(self, space_id: int, document_id: int, requested_by: int, version_no: int, status: str = "queued", artifact_path: str | None = None, error_message: str | None = None) -> DocExport: ...
    def create_document(self, space_id: int, title: str, content_md: str, owner_id: int, permission: DocumentPermission, folder_id: int | None = None) -> Document: ...
    def create_folder(self, space_id: int, parent_id: int | None, name: str, created_by: int) -> Folder: ...
    def create_import_job(self, space_id: int, source_filename: str, created_by: int) -> ImportJob: ...
    def create_quick_entry(self, space_id: int, owner_id: int, title: str, content_md: str = "", source: str | None = None, target_document_id: int | None = None, created_document_id: int | None = None, status: str = "draft") -> QuickEntry: ...
    def create_session(self, user_id: int, current_space_id: int | None, token_hash: str, expires_at: str, client_ua: str | None = None, client_ip: str | None = None) -> Session: ...
    def create_tag(self, space_id: int, name: str, normalized_name: str, created_by: int, color: str | None = None, description: str | None = None) -> Tag: ...
    def create_term(self, space_id: int | None, term: str, definition: str, aliases: list[str], owner_id: int, status: TermStatus, source_document_id: int | None = None, category_id: int | None = None, category: str | None = None, source: str | None = None) -> Term: ...
    def create_term_category(self, space_id: int, parent_id: int | None, name: str, created_by: int) -> TermCategory: ...
    def create_user_with_personal_space(self, email: str, external_id: str, name: str, password_hash: str) -> User: ...
    def delete_document(self, document_id: int) -> None: ...
    def delete_folder(self, folder_id: int) -> None: ...
    def delete_term(self, term_id: int) -> None: ...
    def delete_term_category(self, category_id: int) -> None: ...
    def fail_import_job(self, import_id: int, error: str) -> ImportJob: ...
    def find_document_id_by_title(self, space_id: int, title: str) -> int | None: ...
    def find_folder_by_name(self, space_id: int, parent_id: int | None, name: str) -> Folder | None: ...
    def find_session_by_token_hash(self, token_hash: str) -> Session | None: ...
    def find_space(self, space_id: int) -> Space | None: ...
    def find_term_category_by_name(self, space_id: int, parent_id: int | None, name: str) -> TermCategory | None: ...
    def find_user_by_email(self, email: str) -> User | None: ...
    def find_user_by_external_id(self, external_id: str) -> User | None: ...
    def find_user_by_id(self, user_id: int) -> User | None: ...
    def find_user_by_reset_token_hash(self, token_hash: str) -> User | None: ...
    def first_space_id_for_user(self, user_id: int) -> int | None: ...
    def get_doc_export(self, export_id: int) -> DocExport | None: ...
    def get_document(self, document_id: int) -> Document | None: ...
    def get_document_version(self, document_id: int, version_no: int) -> DocumentVersion | None: ...
    def get_folder(self, folder_id: int) -> Folder | None: ...
    def get_quick_entry(self, entry_id: int) -> QuickEntry | None: ...
    def get_tag(self, tag_id: int) -> Tag | None: ...
    def get_term(self, term_id: int) -> Term | None: ...
    def get_term_category(self, category_id: int) -> TermCategory | None: ...
    def is_descendant_folder(self, space_id: int, ancestor_id: int, candidate_id: int) -> bool: ...
    def is_descendant_term_category(self, space_id: int, ancestor_id: int, candidate_id: int) -> bool: ...
    def is_folder_empty(self, space_id: int, folder_id: int) -> bool: ...
    def is_term_category_empty(self, space_id: int, category_id: int) -> bool: ...
    def list_all_document_chunks(self) -> list[DocumentChunk]: ...
    def list_doc_links(self, space_id: int, document_id: int, direction: str) -> list[DocLink]: ...
    def list_document_chunks(self, document_id: int) -> list[DocumentChunk]: ...
    def list_document_tag_links(self, document_id: int) -> list[TagLink]: ...
    def list_document_versions(self, document_id: int) -> list[DocumentVersion]: ...
    def list_documents(self) -> list[Document]: ...
    def list_folder_document_ids(self, space_id: int, folder_id: int) -> list[int]: ...
    def list_folders(self, space_id: int) -> list[Folder]: ...
    def list_memberships(self) -> list[SpaceMember]: ...
    def list_quick_entries(self, space_id: int, owner_id: int, status: str | None = None) -> list[QuickEntry]: ...
    def list_sessions(self, user_id: int) -> list[Session]: ...
    def list_space_members(self, space_id: int) -> list[SpaceMemberDetail]: ...
    def list_spaces(self) -> list[Space]: ...
    def list_tag_document_ids(self, tag_id: int) -> list[int]: ...
    def list_tags(self, space_id: int, q: str | None = None, status: str | None = "active") -> list[Tag]: ...
    def list_term_categories(self, space_id: int) -> list[TermCategory]: ...
    def list_term_category_term_ids(self, space_id: int, category_id: int) -> list[int]: ...
    def list_terms(self) -> list[Term]: ...
    def list_users(self, q: str = "", role: str = "", status: str = "") -> list[User]: ...
    def move_folder(self, folder_id: int, parent_id: int | None) -> Folder | None: ...
    def move_term_category(self, category_id: int, parent_id: int | None) -> TermCategory | None: ...
    def recall_chunks(self, document_ids: list[int], query: str, limit: int, threshold: float = 0.6) -> list[DocumentChunk]: ...
    def record_login_failure(self, user_id: int) -> int: ...
    def remove_document_tag(self, tag_id: int, document_id: int) -> bool: ...
    def remove_space_member(self, space_id: int, user_id: int) -> bool: ...
    def rename_folder(self, folder_id: int, name: str) -> Folder | None: ...
    def rename_term_category(self, category_id: int, name: str) -> TermCategory | None: ...
    def reorder_folders(self, space_id: int, ordered_folder_ids: list[int]) -> None: ...
    def reorder_term_categories(self, space_id: int, ordered_category_ids: list[int]) -> None: ...
    def replace_document_chunks(self, document_id: int, chunk_texts: list[str]) -> list[DocumentChunk]: ...
    def replace_document_wikilinks(self, space_id: int, source_document_id: int, drafts: list[DocLinkDraft]) -> list[DocLink]: ...
    def require_document(self, document_id: int) -> Document: ...
    def require_import_job(self, import_id: int) -> ImportJob: ...
    def require_term(self, term_id: int) -> Term: ...
    def reset_login_failures(self, user_id: int) -> None: ...
    def restore_document_version(self, document_id: int, version_no: int, editor_id: int) -> Document: ...
    def revoke_all_sessions(self, user_id: int) -> int: ...
    def revoke_session(self, session_id: int, user_id: int) -> bool: ...
    def revoke_user_sessions(self, user_id: int) -> int: ...
    def search_chunks(self, document_ids: list[int], query: str, limit: int) -> list[DocumentChunk]: ...
    def search_users(self, q: str = "") -> list[User]: ...
    def set_document_folder(self, document_id: int, folder_id: int | None) -> None: ...
    def set_locked_until(self, user_id: int, locked_until: str) -> None: ...
    def set_reset_token(self, user_id: int, token_hash: str, expires_at: str) -> None: ...
    def set_user_status(self, user_id: int, status: str) -> User | None: ...
    def update_doc_export(self, export_id: int, status: str, artifact_path: str | None = None, error_message: str | None = None) -> DocExport: ...
    def update_document(self, document_id: int, title: str, content_md: str, permission: DocumentPermission, editor_id: int) -> Document: ...
    def update_password(self, user_id: int, password_hash: str) -> None: ...
    def update_quick_entry(self, entry_id: int, status: str | None = None, target_document_id: int | None = None, created_document_id: int | None = None) -> QuickEntry | None: ...
    def update_session_space(self, session_id: int, space_id: int) -> Session: ...
    def update_space_member_role(self, space_id: int, user_id: int, role: str) -> SpaceMemberDetail | None: ...
    def update_tag(self, tag_id: int, name: str | None = None, normalized_name: str | None = None, color: str | None = None, description: str | None = None, status: str | None = None) -> Tag | None: ...
    def update_term(self, term_id: int, term: str, definition: str, aliases: list[str], status: TermStatus, source_document_id: int | None = None, category_id: int | None = None, category: str | None = None, source: str | None = None) -> Term: ...
    def update_user_role(self, user_id: int, role: str) -> User | None: ...
    def upsert_document_tag(self, tag_id: int, document_id: int, link_source: str, created_by: int) -> TagLink: ...
    def upsert_manual_link(self, space_id: int, source_document_id: int, target_document_id: int | None, target_title: str, link_text: str) -> DocLink: ...
